"""Demand forecasting for the /api/forecast endpoint.

Fits a RandomForest over an item's historical sales and projects demand
seven days out. Kept separate from the Flask app and takes the db handle
as an argument so it stays easy to test.
"""
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from datetime import datetime, timezone

def forecast_demand(db, item_id):
    """Return a forecast dict for item_id, or None when there is no history."""
    historical_data = list(db.historical_data.find({"item_id": item_id}).sort("date", 1))

    if not historical_data:
        return None

    first_date = historical_data[0]["date"]
    X_raw = []
    y_raw = []
    for record in historical_data:
        days_since = (record["date"] - first_date).days
        X_raw.append(days_since)
        y_raw.append(record["quantity_sold"])

    # 1. Convert X and y into a pandas DataFrame
    df = pd.DataFrame({"days_since": X_raw, "quantity_sold": y_raw})

    # 2. Remove Outliers using IQR method
    Q1 = df['quantity_sold'].quantile(0.25)
    Q3 = df['quantity_sold'].quantile(0.75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df['quantity_sold'] >= lower_bound) & (df['quantity_sold'] <= upper_bound)]

    # 3. Data Smoothing: Simple Moving Average (window=3)
    df['quantity_sold'] = df['quantity_sold'].rolling(window=3).mean()

    # 4. Drop any NaN values generated by the rolling window
    df.dropna(inplace=True)

    # 5. Extract the cleaned and smoothed values back into X (2D) and y (1D)
    X = df[['days_since']].values
    y = df['quantity_sold'].values

    # 6. Fit the RandomForestRegressor model on cleaned data
    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X, y)

    y_pred = model.predict(X)
    mape = np.mean(np.abs((y - y_pred) / y))
    confidence_level = max(0.0, min(1.0, 1 - mape))

    # 7. Predict the target value for last_days_since + 7
    last_days_since = (historical_data[-1]["date"] - first_date).days
    target_days = np.array([[last_days_since + 7]])
    predicted_demand = model.predict(target_days)[0]

    # Persist the calculated metrics to the analytical database collection
    forecast_entry = {
        "forecast_id": int(datetime.now(timezone.utc).timestamp()),
        "item_id": item_id,
        "predicted_demand": round(float(predicted_demand), 2),
        "confidence_level": float(confidence_level),
        "forecast_date": datetime.now(timezone.utc)
    }
    db.demand_forecasts.insert_one(forecast_entry)

    # Mocking statistical engine return schema with required predictive attributes
    return {
        "item_id": item_id,
        "predicted_demand": round(float(predicted_demand), 2),
        "confidence_level": float(confidence_level),
        "message": "Demand forecast generated successfully"
    }